// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InstallSelectedLibs(arg1:string,arg2:Array<string>):Promise<void>;

export function RequestFolderSelection():Promise<void>;

export function RequestLibsData():Promise<void>;
