// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InstallSelectedLibs(arg1, arg2) {
  return window['go']['main']['App']['InstallSelectedLibs'](arg1, arg2);
}

export function RequestFolderSelection() {
  return window['go']['main']['App']['RequestFolderSelection']();
}

export function RequestLibsData() {
  return window['go']['main']['App']['RequestLibsData']();
}
